//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBSlink.Android
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int cellback = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int fontdescription = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int fonttittle = 2131034113;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int CustomSelector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int email = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int email_go = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int email_open = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_tab_artists_grey = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_tab_artists_white = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_key = 2130837512;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int CCloudViewDescription = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int CCloudViewImage = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int CCloudViewLinearLayout = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int CCloudViewTittle = 2131165188;
			
			// aapt resource value: 0x7f070019
			public const int LstCloudsList = 2131165209;
			
			// aapt resource value: 0x7f07001b
			public const int LstPMList = 2131165211;
			
			// aapt resource value: 0x7f07002b
			public const int LstUsersList = 2131165227;
			
			// aapt resource value: 0x7f07002e
			public const int PMViewDescription = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int PMViewImage = 2131165231;
			
			// aapt resource value: 0x7f07002c
			public const int PMViewLinearLayout = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int PMViewTittle = 2131165229;
			
			// aapt resource value: 0x7f07003e
			public const int UsersViewDescription = 2131165246;
			
			// aapt resource value: 0x7f07003f
			public const int UsersViewImage = 2131165247;
			
			// aapt resource value: 0x7f07003c
			public const int UsersViewLinearLayout = 2131165244;
			
			// aapt resource value: 0x7f07003d
			public const int UsersViewTittle = 2131165245;
			
			// aapt resource value: 0x7f07000d
			public const int btnChatSend = 2131165197;
			
			// aapt resource value: 0x7f070016
			public const int btnCloudsAdd = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int btnCloudsRefresh = 2131165207;
			
			// aapt resource value: 0x7f070032
			public const int btnConnect = 2131165234;
			
			// aapt resource value: 0x7f070037
			public const int btnConnectCloud = 2131165239;
			
			// aapt resource value: 0x7f070033
			public const int btnExit = 2131165235;
			
			// aapt resource value: 0x7f070036
			public const int btnGetClouds = 2131165238;
			
			// aapt resource value: 0x7f070039
			public const int btnLeaveCloud = 2131165241;
			
			// aapt resource value: 0x7f07003b
			public const int btnSendChat = 2131165243;
			
			// aapt resource value: 0x7f07003a
			public const int btnSendPM = 2131165242;
			
			// aapt resource value: 0x7f070029
			public const int btnSettingsDelete = 2131165225;
			
			// aapt resource value: 0x7f070028
			public const int btnSettingsReconnect = 2131165224;
			
			// aapt resource value: 0x7f070027
			public const int btnSettingsSave = 2131165223;
			
			// aapt resource value: 0x7f070034
			public const int btnStart = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int btnStop = 2131165237;
			
			// aapt resource value: 0x7f070009
			public const int chat_ScrollView = 2131165193;
			
			// aapt resource value: 0x7f070020
			public const int chkSettingsJoinLeave = 2131165216;
			
			// aapt resource value: 0x7f07001f
			public const int chkSettingsPlayNewMessage = 2131165215;
			
			// aapt resource value: 0x7f070023
			public const int lblSettingsCloudServerHost = 2131165219;
			
			// aapt resource value: 0x7f070025
			public const int lblSettingsCloudServerPort = 2131165221;
			
			// aapt resource value: 0x7f07001d
			public const int lblSettingsNickName = 2131165213;
			
			// aapt resource value: 0x7f07000f
			public const int lblTabCloudsCloudname = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int lblTabCloudsMax = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int lblTabCloudsPassword = 2131165201;
			
			// aapt resource value: 0x7f07000b
			public const int linearLayout1 = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int linearLayout2 = 2131165198;
			
			// aapt resource value: 0x7f070015
			public const int linearLayout3 = 2131165205;
			
			// aapt resource value: 0x7f070007
			public const int scrollLogGeneral = 2131165191;
			
			// aapt resource value: 0x7f07001c
			public const int scrollSettingsGeneral = 2131165212;
			
			// aapt resource value: 0x7f070002
			public const int textView1 = 2131165186;
			
			// aapt resource value: 0x7f070021
			public const int textView2 = 2131165217;
			
			// aapt resource value: 0x7f070000
			public const int textView3 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int textView4 = 2131165185;
			
			// aapt resource value: 0x7f07000a
			public const int txtChatGeneral = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int txtChatMessage = 2131165196;
			
			// aapt resource value: 0x7f070038
			public const int txtCloud = 2131165240;
			
			// aapt resource value: 0x7f070018
			public const int txtCloudsCount = 2131165208;
			
			// aapt resource value: 0x7f070013
			public const int txtCloudsMax = 2131165203;
			
			// aapt resource value: 0x7f070012
			public const int txtCloudsName = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int txtCloudsPassword = 2131165204;
			
			// aapt resource value: 0x7f070030
			public const int txtIp = 2131165232;
			
			// aapt resource value: 0x7f070031
			public const int txtLog = 2131165233;
			
			// aapt resource value: 0x7f070008
			public const int txtLogGeneral = 2131165192;
			
			// aapt resource value: 0x7f07001a
			public const int txtPMCount = 2131165210;
			
			// aapt resource value: 0x7f070024
			public const int txtSettingsCloudServerHost = 2131165220;
			
			// aapt resource value: 0x7f070026
			public const int txtSettingsCloudServerPort = 2131165222;
			
			// aapt resource value: 0x7f070022
			public const int txtSettingsIPInternalServer = 2131165218;
			
			// aapt resource value: 0x7f07001e
			public const int txtSettingsNickName = 2131165214;
			
			// aapt resource value: 0x7f07002a
			public const int txtUsersCount = 2131165226;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CloudView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Log = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainTab = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MainTabChat = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MainTabClouds = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MainTabPM = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MainTabSettings = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int MainTabUsers = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int PMView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Test1 = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int TestButtons = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int UsersView = 2130903052;
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int incoming_chat_msg = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int new_node = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int node_left = 2130968578;
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			private String()
			{
			}
		}
	}
}
