//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.225
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBSlink.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XBSlink.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi0\deflang1031\deflangfe1031\themelang1031\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f1\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}
        ///{\f2\fbidi \fmodern\fcharset0\fprq1{\*\panose 02070309020205020404}Courier New;}{\f3\fbidi \froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}{\f10\fbidi \fnil\ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string about_xbslink {
            get {
                return ResourceManager.GetString("about_xbslink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, XBSlink crashed.
        ///Please send this info to xbslink@secudb.de, we might have the right bug spray ;) Thank you! ähnelt.
        /// </summary>
        internal static string crash_message {
            get {
                return ResourceManager.GetString("crash_message", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap error_50 {
            get {
                object obj = ResourceManager.GetObject("error_50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_key {
            get {
                object obj = ResourceManager.GetObject("icon_key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XBSlink could not find any capture devices in your system.
        ///This problem occurs if the WinPCap library is not active. Please make sure WinPCap is loaded.
        ///
        ///For more information see &lt;http://www.secudb.de/~seuffert/xbslink/faq#question-15&gt; ähnelt.
        /// </summary>
        internal static string message_no_capture_devices {
            get {
                return ResourceManager.GetString("message_no_capture_devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XBSlink could not find any capture devices in your system.
        ///This problem occurs if the WinPCap library is not active. Please make sure WinPCap is loaded.
        ///
        ///Do you want XBSlink to try starting the WinPcap driver (NPF) ? ähnelt.
        /// </summary>
        internal static string message_no_capture_devices_startNPF {
            get {
                return ResourceManager.GetString("message_no_capture_devices_startNPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XBSlink could not find any capture devices in your system.
        ///This problem occurs if the user has not enough rights to use the pcap library. Please try to run XBSlink as root (&quot;sudo mono XBSlink.exe&quot;)
        ///
        ///For more information see &lt;http://www.secudb.de/~seuffert/xbslink/faq#question-2&gt; ähnelt.
        /// </summary>
        internal static string message_no_capture_devices_unix {
            get {
                return ResourceManager.GetString("message_no_capture_devices_unix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please add at least one MAC address to the list. ähnelt.
        /// </summary>
        internal static string message_specialmaclist_empty {
            get {
                return ResourceManager.GetString("message_specialmaclist_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.secudb.de/~seuffert/xbslink/latest_xbslink_version ähnelt.
        /// </summary>
        internal static string url_check_latest_version {
            get {
                return ResourceManager.GetString("url_check_latest_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.secudb.de/~seuffert/xbslink/latest_xbslink_version_linux ähnelt.
        /// </summary>
        internal static string url_check_latest_version_linux {
            get {
                return ResourceManager.GetString("url_check_latest_version_linux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.secudb.de/~seuffert/xbslink/latest_xbslink_version_mac ähnelt.
        /// </summary>
        internal static string url_check_latest_version_mac {
            get {
                return ResourceManager.GetString("url_check_latest_version_mac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.secudb.de/~seuffert/xbslink/ ähnelt.
        /// </summary>
        internal static string url_xbslink_website {
            get {
                return ResourceManager.GetString("url_xbslink_website", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon XBSlink {
            get {
                object obj = ResourceManager.GetObject("XBSlink", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
