/**
 * Project: XBSlink: A XBox360 & PS3/2 System Link Proxy
 * File name: Resources.Designer.cs
 *   
 * @author Oliver Seuffert, Copyright (C) 2011.
 */
/* 
 * XBSlink is free software; you can redistribute it and/or modify 
 * it under the terms of the GNU General Public License as published by 
 * the Free Software Foundation; either version 2 of the License, or 
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but 
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License 
 * for more details.
 * 
 * You should have received a copy of the GNU General Public License along 
 * with this program; If not, see <http://www.gnu.org/licenses/>
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBSlink.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XBSlink.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {\rtf1\ansi\ansicpg1252\deff0\deflang1031{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Msftedit 5.41.21.2509;}\viewkind4\uc1\pard\sa200\sl240\slmult1\lang7\b\f0\fs28 About XBSlink\b0\fs32\par
        ///\fs18 XBSlink is a system link proxy for the XBox360 to play system link games over a internet connection.\line\par
        ///\ul Usage\ulnone :\par
        ///\pard{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-360\li720\sa200\sl240\slmult1 in the settings  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string about_xbslink {
            get {
                return ResourceManager.GetString("about_xbslink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, XBSlink crashed.
        ///Please send this info to xbslink@secudb.de, we might have the right bug spray ;) Thank you! ähnelt.
        /// </summary>
        internal static string crash_message {
            get {
                return ResourceManager.GetString("crash_message", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap error_50 {
            get {
                object obj = ResourceManager.GetObject("error_50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_key {
            get {
                object obj = ResourceManager.GetObject("icon_key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XBSlink could not find any capture devices in your system.
        ///This problem occurs if the WinPCap library is not active. Please make sure WinPCap is loaded.
        ///
        ///For more information see &lt;http://www.secudb.de/~seuffert/xbslink/faq#question-15&gt; ähnelt.
        /// </summary>
        internal static string message_no_capture_devices {
            get {
                return ResourceManager.GetString("message_no_capture_devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XBSlink could not find any capture devices in your system.
        ///This problem occurs if the WinPCap library is not active. Please make sure WinPCap is loaded.
        ///
        ///Do you want XBSlink to try starting the WinPcap driver (NPF) ? ähnelt.
        /// </summary>
        internal static string message_no_capture_devices_startNPF {
            get {
                return ResourceManager.GetString("message_no_capture_devices_startNPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.secudb.de/~seuffert/xbslink/latest_xbslink_version ähnelt.
        /// </summary>
        internal static string url_check_latest_version {
            get {
                return ResourceManager.GetString("url_check_latest_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.secudb.de/~seuffert/xbslink/ ähnelt.
        /// </summary>
        internal static string url_xbslink_website {
            get {
                return ResourceManager.GetString("url_xbslink_website", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon XBSlink {
            get {
                object obj = ResourceManager.GetObject("XBSlink", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
