//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBSLink.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool REG_CHAT_SOUND_NOTIFICATION {
            get {
                return ((bool)(this["REG_CHAT_SOUND_NOTIFICATION"]));
            }
            set {
                this["REG_CHAT_SOUND_NOTIFICATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool REG_NEW_NODE_SOUND_NOTIFICATION {
            get {
                return ((bool)(this["REG_NEW_NODE_SOUND_NOTIFICATION"]));
            }
            set {
                this["REG_NEW_NODE_SOUND_NOTIFICATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.secudb.de/~seuffert/xbslink/cloudlist/")]
        public string REG_CLOUDLIST_SERVER {
            get {
                return ((string)(this["REG_CLOUDLIST_SERVER"]));
            }
            set {
                this["REG_CLOUDLIST_SERVER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool REG_USE_CLOUDLIST_SERVER_TO_CHECK_INCOMING_PORT {
            get {
                return ((bool)(this["REG_USE_CLOUDLIST_SERVER_TO_CHECK_INCOMING_PORT"]));
            }
            set {
                this["REG_USE_CLOUDLIST_SERVER_TO_CHECK_INCOMING_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool REG_NAT_ENABLE {
            get {
                return ((bool)(this["REG_NAT_ENABLE"]));
            }
            set {
                this["REG_NAT_ENABLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string REG_NAT_IP_POOL {
            get {
                return ((string)(this["REG_NAT_IP_POOL"]));
            }
            set {
                this["REG_NAT_IP_POOL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool REG_FILTER_WELLKNOWN_PORTS {
            get {
                return ((bool)(this["REG_FILTER_WELLKNOWN_PORTS"]));
            }
            set {
                this["REG_FILTER_WELLKNOWN_PORTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool REG_PS3_COMPAT_MODE_ENABLE {
            get {
                return ((bool)(this["REG_PS3_COMPAT_MODE_ENABLE"]));
            }
            set {
                this["REG_PS3_COMPAT_MODE_ENABLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool REG_SNIFFER_EXCLUDE_GATWAY_IPS {
            get {
                return ((bool)(this["REG_SNIFFER_EXCLUDE_GATWAY_IPS"]));
            }
            set {
                this["REG_SNIFFER_EXCLUDE_GATWAY_IPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool REG_CHAT_NODEINFOMESSAGES {
            get {
                return ((bool)(this["REG_CHAT_NODEINFOMESSAGES"]));
            }
            set {
                this["REG_CHAT_NODEINFOMESSAGES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SettingsUpdateNeeded {
            get {
                return ((bool)(this["SettingsUpdateNeeded"]));
            }
            set {
                this["SettingsUpdateNeeded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool REG_SNIFFER_FORWARD_ALL_HIGH_PORT_BROADCASTS {
            get {
                return ((bool)(this["REG_SNIFFER_FORWARD_ALL_HIGH_PORT_BROADCASTS"]));
            }
            set {
                this["REG_SNIFFER_FORWARD_ALL_HIGH_PORT_BROADCASTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool REG_MINIMIZE2SYSTRAY {
            get {
                return ((bool)(this["REG_MINIMIZE2SYSTRAY"]));
            }
            set {
                this["REG_MINIMIZE2SYSTRAY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool REG_PREVENT_SYSTEM_STANDY {
            get {
                return ((bool)(this["REG_PREVENT_SYSTEM_STANDY"]));
            }
            set {
                this["REG_PREVENT_SYSTEM_STANDY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool REG_SHOW_NEWS_FEED {
            get {
                return ((bool)(this["REG_SHOW_NEWS_FEED"]));
            }
            set {
                this["REG_SHOW_NEWS_FEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.secudb.de/~seuffert/xbslink/feed")]
        public string REG_NEWS_FEED_URI {
            get {
                return ((string)(this["REG_NEWS_FEED_URI"]));
            }
            set {
                this["REG_NEWS_FEED_URI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string REG_NEWS_FEED_NEWEST_ID {
            get {
                return ((string)(this["REG_NEWS_FEED_NEWEST_ID"]));
            }
            set {
                this["REG_NEWS_FEED_NEWEST_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool REG_NEWS_FEED_SWITCH_TO_TAB {
            get {
                return ((bool)(this["REG_NEWS_FEED_SWITCH_TO_TAB"]));
            }
            set {
                this["REG_NEWS_FEED_SWITCH_TO_TAB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool REG_CHAT_AUTOSWITCH {
            get {
                return ((bool)(this["REG_CHAT_AUTOSWITCH"]));
            }
            set {
                this["REG_CHAT_AUTOSWITCH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string REG_CHAT_NICKNAME {
            get {
                return ((string)(this["REG_CHAT_NICKNAME"]));
            }
            set {
                this["REG_CHAT_NICKNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string REG_SPECIAL_MAC_LIST {
            get {
                return ((string)(this["REG_SPECIAL_MAC_LIST"]));
            }
            set {
                this["REG_SPECIAL_MAC_LIST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool REG_ONLY_FORWARD_SPECIAL_MACS {
            get {
                return ((bool)(this["REG_ONLY_FORWARD_SPECIAL_MACS"]));
            }
            set {
                this["REG_ONLY_FORWARD_SPECIAL_MACS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool REG_ENABLE_SPECIAL_MAC_LIST {
            get {
                return ((bool)(this["REG_ENABLE_SPECIAL_MAC_LIST"]));
            }
            set {
                this["REG_ENABLE_SPECIAL_MAC_LIST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool REG_USE_UPNP {
            get {
                return ((bool)(this["REG_USE_UPNP"]));
            }
            set {
                this["REG_USE_UPNP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31415")]
        public int REG_REMOTE_PORT {
            get {
                return ((int)(this["REG_REMOTE_PORT"]));
            }
            set {
                this["REG_REMOTE_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string REG_REMOTE_HOST_HISTORY {
            get {
                return ((string)(this["REG_REMOTE_HOST_HISTORY"]));
            }
            set {
                this["REG_REMOTE_HOST_HISTORY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("otherhost.dyndns.org")]
        public string REG_REMOTE_HOST {
            get {
                return ((string)(this["REG_REMOTE_HOST"]));
            }
            set {
                this["REG_REMOTE_HOST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31415")]
        public int REG_LOCAL_PORT {
            get {
                return ((int)(this["REG_LOCAL_PORT"]));
            }
            set {
                this["REG_LOCAL_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string REG_LOCAL_IP {
            get {
                return ((string)(this["REG_LOCAL_IP"]));
            }
            set {
                this["REG_LOCAL_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string REG_CAPTURE_DEVICE_NAME {
            get {
                return ((string)(this["REG_CAPTURE_DEVICE_NAME"]));
            }
            set {
                this["REG_CAPTURE_DEVICE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool REG_CHECK4UPDATES {
            get {
                return ((bool)(this["REG_CHECK4UPDATES"]));
            }
            set {
                this["REG_CHECK4UPDATES"] = value;
            }
        }
    }
}
